package com.ticketmesh.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.time.Instant;

/**
 * A referral invite generated by a user. The invitee email is stored encrypted
 * at rest (set to ciphertext by the service layer) and the referrer is rewarded
 * loyalty points when the invitee joins using the code.
 */
@Entity
@Table(name = "referrals")
public class Referral {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotNull
    @Column(name = "referrer_user_id", nullable = false)
    private Long referrerUserId;

    @Column(name = "invitee_user_id")
    private Long inviteeUserId;

    @Column(name = "invitee_email", length = 512)
    private String inviteeEmail;

    @NotBlank
    @Size(max = 24)
    @Column(nullable = false, unique = true, length = 24)
    private String code;

    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private Status status;

    @Column(name = "reward_points", nullable = false)
    private long rewardPoints;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "joined_at")
    private Instant joinedAt;

    public Referral() {
    }

    public Referral(Long referrerUserId, String code) {
        this.referrerUserId = referrerUserId;
        this.code = code;
        this.status = Status.PENDING;
        this.rewardPoints = 0;
        this.createdAt = Instant.now();
    }

    public Long getId() {
        return id;
    }

    public Long getReferrerUserId() {
        return referrerUserId;
    }

    public Long getInviteeUserId() {
        return inviteeUserId;
    }

    public void setInviteeUserId(Long inviteeUserId) {
        this.inviteeUserId = inviteeUserId;
    }

    public String getInviteeEmail() {
        return inviteeEmail;
    }

    public void setInviteeEmail(String inviteeEmail) {
        this.inviteeEmail = inviteeEmail;
    }

    public String getCode() {
        return code;
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    public long getRewardPoints() {
        return rewardPoints;
    }

    public void setRewardPoints(long rewardPoints) {
        this.rewardPoints = rewardPoints;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getJoinedAt() {
        return joinedAt;
    }

    public void markJoined(Long inviteeUserId) {
        this.inviteeUserId = inviteeUserId;
        this.status = Status.JOINED;
        this.joinedAt = Instant.now();
    }

    public enum Status {
        PENDING,
        JOINED,
        REWARDED
    }
}
