apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ticketmesh.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ticketmesh.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ticketmesh.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ticketmesh.name" . }}
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: ticketmesh-core
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ include "ticketmesh.fullname" . }}
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ticketmesh.fullname" . }}-secrets
                  key: db-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "ticketmesh.fullname" . }}-secrets
                  key: jwt-secret
            - name: QR_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "ticketmesh.fullname" . }}-secrets
                  key: qr-secret
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath }}
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.livenessPath }}
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
