apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ticketmesh.fullname" . }}-secrets
type: Opaque
stringData:
  db-password: {{ .Values.secrets.dbPassword | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  qr-secret: {{ .Values.secrets.qrSecret | quote }}
