-- V10__kyc_identity.sql
-- KYC identity and address verification fields on the users table.
-- Also adds agent business verification fields.

ALTER TABLE users ADD COLUMN IF NOT EXISTS kyc_id_type VARCHAR(20)  DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS kyc_id_number VARCHAR(60)  DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS kyc_date_of_birth VARCHAR(20)  DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS kyc_gender VARCHAR(20)  DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS kyc_address_line1 VARCHAR(200) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS kyc_address_line2 VARCHAR(200) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS kyc_city VARCHAR(100)  DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS kyc_state VARCHAR(100)  DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS kyc_postal_code VARCHAR(20)  DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS kyc_country_iso VARCHAR(2)  DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS kyc_status VARCHAR(20)  DEFAULT 'PENDING';
ALTER TABLE users ADD COLUMN IF NOT EXISTS kyc_verified_at TIMESTAMP NULL DEFAULT NULL;

ALTER TABLE users ADD COLUMN IF NOT EXISTS biz_name VARCHAR(160)  DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS biz_reg_number VARCHAR(60)  DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS biz_tax_id VARCHAR(60)  DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS biz_type VARCHAR(20)  DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS biz_address VARCHAR(400) DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS biz_status VARCHAR(20)  DEFAULT 'PENDING';
ALTER TABLE users ADD COLUMN IF NOT EXISTS biz_verified_at TIMESTAMP NULL DEFAULT NULL;
